export const ErrorCode = {
  BAD_REQUEST: "BAD_REQUEST",
  EXTERNAL_API_ERROR: "EXTERNAL_API_ERROR",
  EXTERNAL_API_FORBIDDEN: "EXTERNAL_API_FORBIDDEN",
  EXTERNAL_API_NOT_FOUND: "EXTERNAL_API_NOT_FOUND",
  EXTERNAL_API_UNAVAILABLE: "EXTERNAL_API_UNAVAILABLE",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  NOT_FOUND: "NOT_FOUND",
  TRANSACTION_NOT_FOUND: "TRANSACTION_NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
} as const

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode]
